### ISSUE TITLE
没有呀

### ISSUE THREAD

**Issue by ABC15768** [1446445040/clock#2]
没有打卡

**Comment by emosheeep** [comment]
<img width="387" alt="截屏2022-03-24 11 48 29" src="https://user-images.githubusercontent.com/31957758/159838355-79e2ceca-4392-4c37-8351-982b9d4ffa9a.png">

**Comment by ABC15768** [comment]
我的没有

**Comment by ABC15768** [comment]
![image](https://user-images.githubusercontent.com/93878172/159838659-66947e08-e597-4939-b8bc-3629179c0ec8.png)

**Comment by ABC15768** [comment]
昨天就设置好了

**Comment by emosheeep** [comment]
这个随缘了哈，并发请求有点多可能没有成功，你可以明天再看看，或者手动点击打卡。毕业工作了，我现在已经没有时间和精力维护这个小程序了，见谅。
